# Generated by Django 4.2.17 on 2025-04-11 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clothing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="商品名称")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="商品描述"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="clothing_images/",
                        verbose_name="商品图片",
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="库存量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={"verbose_name": "服装商品", "verbose_name_plural": "服装商品",},
        ),
        migrations.CreateModel(
            name="ClothingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="类型名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="类型描述"),
                ),
            ],
            options={"verbose_name": "服装类型", "verbose_name_plural": "服装类型",},
        ),
        migrations.CreateModel(
            name="PriceRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="区间名称")),
                (
                    "min_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="最低价"
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="最高价"
                    ),
                ),
            ],
            options={"verbose_name": "价格区间", "verbose_name_plural": "价格区间",},
        ),
        migrations.CreateModel(
            name="RatingCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="评价类别")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="评价描述"),
                ),
            ],
            options={"verbose_name": "评价类别", "verbose_name_plural": "评价类别",},
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="地区名称")),
                ("code", models.CharField(max_length=20, verbose_name="地区代码")),
            ],
            options={"verbose_name": "地区", "verbose_name_plural": "地区",},
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=50, unique=True, verbose_name="订单编号"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="订单总额"
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="订单日期"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales_analysis.region",
                        verbose_name="地区",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={"verbose_name": "销售订单", "verbose_name_plural": "销售订单",},
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1星"), (2, "2星"), (3, "3星"), (4, "4星"), (5, "5星")],
                        verbose_name="评分",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="评价内容"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评价时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales_analysis.ratingcategory",
                        verbose_name="评价类别",
                    ),
                ),
                (
                    "clothing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales_analysis.clothing",
                        verbose_name="服装商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={"verbose_name": "商品评价", "verbose_name_plural": "商品评价",},
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="数量")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "clothing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales_analysis.clothing",
                        verbose_name="服装商品",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales_analysis.salesorder",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={"verbose_name": "订单条目", "verbose_name_plural": "订单条目",},
        ),
        migrations.AddField(
            model_name="clothing",
            name="clothing_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sales_analysis.clothingtype",
                verbose_name="服装类型",
            ),
        ),
        migrations.AddField(
            model_name="clothing",
            name="price_range",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sales_analysis.pricerange",
                verbose_name="价格区间",
            ),
        ),
    ]
